from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .forms import AuditionForm

class AuditionListView: ...

class AuditionCreateView: ...

class AuditionUpdateView: ...

class AuditionDeleteView: ...
