# Generated by Django 5.2 on 2025-11-05 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0004_alter_audition_name'),
        ('auditioner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditioner',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditioner',
            name='audition',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='audition.audition'),
        ),
    ]
