# Generated by Django 5.2 on 2025-04-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "deadline",
                    models.DateTimeField(blank=True, null=True, verbose_name="dl"),
                ),
                (
                    "annc_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="annc"),
                ),
                (
                    "conc_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="conc"),
                ),
                ("poster", models.ImageField(upload_to="audition/posters/")),
            ],
        ),
    ]
