# Generated by Django 5.2 on 2025-11-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0004_alter_audition_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='audition',
            name='elig_crit',
            field=models.JSONField(default=dict),
        ),
    ]
